#!/bin/bash
# place to keep our cached blocklists
LISTDIR="/var/cache/blocklists"

# create cache directory for our lists if it isn't there
[ ! -d $LISTDIR ] && mkdir $LISTDIR

# countries to block, must be lcase
# http://www.ipdeny.com/ipblocks/data/countries/
COUNTRIES=(af ae ir iq tr cn sa sy ru ua hk id kz kw ly)

# bluetack lists to use - they now obfuscate these so get them from
# https://www.iblocklist.com/lists.php
BLUETACKALIAS=(DShield Bogon Hijacked DROP ForumSpam WebExploit Proxies BadSpiders CruzIT Zeus Palevo Malicious Malcode)
BLUETACK=(xpbqleszmajjesnzddhv lujdnbasfaaixitgmxpp usrcshglbiilevmyfhse zbdlwrqkabxbcppvrnos ficutxiwawokxlcyoeye ghlzqtqxnzctvvajwwag xoebmbyexwuiogmbyprb mcvxsnihddgutbjfbghy czvaehmjpsnwwttrdoyl ynkdjqsjyfmilsgbogqf erqajhwrxiuvjxqrrwfj npkuuhuxcsllnhoamkvm pbqcylkejciyhmwttify)

# disabled bluetack lists
# BLUETACKALIAS=(Ads Adservers)
# BLUETACK=(dgxtneitpuvgqqcpfulq zhogegszwduurnvsyhdf)

# NOW + 12 hours
MAX_MTIME=$(($(date +"%s")+12*60*60))

ipset create -exist blocks hash:net maxelem 4294967295
ipset create -exist blocks-tmp hash:net maxelem 4294967295
ipset flush blocks-tmp

# TOR
# https://check.torproject.org/exit-addresses
echo "Importing TOR blocks..."
if [ ! -f $LISTDIR/tor-exit-addresses.txt ] || [ $(stat --printf="%Y" $LISTDIR/tor-exit-addresses.txt) -gt $MAX_MTIME ]; then
    wget -q https://check.torproject.org/exit-addresses -O $LISTDIR/tor-exit-addresses.txt
fi
awk '!x[$0]++' $LISTDIR/tor-exit-addresses.txt | grep ExitAddress | awk '{ print "add -exist blocks-tmp ",$2 }' | ipset restore

# country zones
echo "Importing country zones..."
for country in ${COUNTRIES[@]}; do
    if [ ! -f $LISTDIR/$country.zone ] || [ $(stat --printf="%Y" $LISTDIR/$country.zone) -gt $MAX_MTIME ]; then
        wget -q http://www.ipdeny.com/ipblocks/data/countries/$country.zone -O $LISTDIR/$country.zone
        fi
    awk '!x[$0]++' $LISTDIR/$country.zone | grep  -v \# | grep -v ^$ |  grep -v 127\.0\.0 | sed -e "s/^/add\ \-exist\ blocks\-tmp\ /" | ipset restore
done

# iblocklists
echo "Importing iblocklists..."
i=0
for list in ${BLUETACK[@]}; do
    if [ ! -f $LISTDIR/${BLUETACKALIAS[i]} ] || [ $(stat --printf="%Y" $LISTDIR/${BLUETACKALIAS[i]}) -gt $MAX_MTIME ]; then
        wget -q "http://list.iblocklist.com/?list=${list}&fileformat=p2p&archiveformat=gz" -O $LISTDIR/${BLUETACKALIAS[i]}.gz
        gunzip $LISTDIR/${BLUETACKALIAS[i]}.gz
    fi
    awk '!x[$0]++' $LISTDIR/${BLUETACKALIAS[i]} | grep  -v \# | grep -v ^$ |  grep -v 127\.0\.0 | awk '{split($0,a,":"); print "add -exist blocks-tmp ",a[2]}' | ipset restore
    i=$((i+1))
done

# apply
ipset swap blocks blocks-tmp
ipset destroy blocks-tmp

# iptables
IPTABLES=$(iptables-save)
if ! echo $IPTABLES|grep -q "\-A\ INPUT\ \-m\ set\ \-\-match\-set\ blocks\ src\ \-\j\ DROP"; then
    iptables -I INPUT 1 -m set --match-set blocks src -j DROP
fi
if ! echo $IPTABLES|grep -q "\-A\ OUTPUT\ \-m\ set\ \-\-match\-set\ blocks\ dst\ \-\j\ REJECT"; then
    iptables -I OUTPUT 1 -m set --match-set blocks dst -j REJECT
fi
