post_install() {
	usr/bin/systemctl daemon-reload
	usr/bin/systemctl --global enable php56-fpm
	usr/bin/systemctl --global enable php70-fpm
	usr/bin/getent group web > /dev/null || usr/bin/groupadd -r -g 666 web
	usr/bin/setfacl -m group:web:--- /usr/bin/passwd
}

post_upgrade() {
	post_install
	usr/bin/systemctl try-restart goweb
	usr/bin/goweb user reapply-all
}

pre_remove() {
	usr/bin/systemctl --global disable php56-fpm
	usr/bin/systemctl --global disable php70-fpm
}